/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scraper;

import static scraper.Constants.MONGO_CONNECTION;
import static scraper.Constants.MONGO_DB;

import java.util.List;
import java.util.ArrayList;

import org.bson.Document;

import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoCollection;
import com.mongodb.MongoClientSettings;

public class App {

    private static void tryDrop(MongoDatabase database, String collection) {
        try {
            MongoCollection<Document> senate = database.getCollection(collection); 
            senate.drop();
        } catch (IllegalArgumentException e) {
            System.out.println(e);
        }

    }

    private static void writeToMongo(Senator[] senators) {
        String collection = "senate";
        MongoClientSettings settings = MongoClientSettings.builder()
            .applyConnectionString(MONGO_CONNECTION)
            .retryWrites(true)
            .build();

        MongoClient mongoClient = MongoClients.create(settings);
        MongoDatabase database = mongoClient.getDatabase(MONGO_DB);  
        tryDrop(database, collection);     
        
        database.createCollection(collection);
        MongoCollection<Document> senate = database.getCollection(collection); 
        List<Document> docs = new ArrayList<Document>();
        for (Senator s: senators) {
            docs.add(s.toDocument());
        }
        senate.insertMany(docs);    
    }

    public static void main(String[] args) {
        Senator[] senators = SenateController.senate();
        writeToMongo(senators);
    }
}
